name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: public
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy site files to public/
        run: |
          rm -rf public || true
          mkdir -p public
          cp -R lvl/* public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
