name: Deploy site to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ main ]

# Ensure the workflow has the permissions needed to push to gh-pages using the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare public directory
        run: |
          rm -rf public || true
          mkdir -p public
          cp -R lvl/* public/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
